# Setup
title:               Josh Bochu
tagline:             'weblog'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 "https://joshbochu.com"
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Josh Bochu
  url:               https://twitter.com/joshbochu
  email:             joshuatbochu@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
